/* 
 * OpenALPR Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using OpenAlprApi.Client;
using OpenAlprApi.Api;
using OpenAlprApi.Model;

namespace OpenAlprApi.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        
        /// <summary>
        /// Test RecognizeBytes
        /// </summary>
        [Test]
        public void RecognizeBytesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string imageBytes = null;
            //string secretKey = null;
            //string country = null;
            //int? recognizeVehicle = null;
            //string state = null;
            //int? returnImage = null;
            //int? topn = null;
            //string prewarp = null;
            //var response = instance.RecognizeBytes(imageBytes, secretKey, country, recognizeVehicle, state, returnImage, topn, prewarp);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test RecognizeFile
        /// </summary>
        [Test]
        public void RecognizeFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream image = null;
            //string secretKey = null;
            //string country = null;
            //int? recognizeVehicle = null;
            //string state = null;
            //int? returnImage = null;
            //int? topn = null;
            //string prewarp = null;
            //var response = instance.RecognizeFile(image, secretKey, country, recognizeVehicle, state, returnImage, topn, prewarp);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test RecognizeUrl
        /// </summary>
        [Test]
        public void RecognizeUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string imageUrl = null;
            //string secretKey = null;
            //string country = null;
            //int? recognizeVehicle = null;
            //string state = null;
            //int? returnImage = null;
            //int? topn = null;
            //string prewarp = null;
            //var response = instance.RecognizeUrl(imageUrl, secretKey, country, recognizeVehicle, state, returnImage, topn, prewarp);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
    }

}
