/**
 * OpenALPR Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenalprApi);
  }
}(this, function(expect, OpenalprApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenalprApi.PlateDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlateDetails', function() {
    it('should create an instance of PlateDetails', function() {
      // uncomment below and update the code to test PlateDetails
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be.a(OpenalprApi.PlateDetails);
    });

    it('should have the property plate (base name: "plate")', function() {
      // uncomment below and update the code to test the property plate
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property matchesTemplate (base name: "matches_template")', function() {
      // uncomment below and update the code to test the property matchesTemplate
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property requestedTopn (base name: "requested_topn")', function() {
      // uncomment below and update the code to test the property requestedTopn
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property processingTimeMs (base name: "processing_time_ms")', function() {
      // uncomment below and update the code to test the property processingTimeMs
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property confidence (base name: "confidence")', function() {
      // uncomment below and update the code to test the property confidence
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "region")', function() {
      // uncomment below and update the code to test the property region
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property regionConfidence (base name: "region_confidence")', function() {
      // uncomment below and update the code to test the property regionConfidence
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property coordinates (base name: "coordinates")', function() {
      // uncomment below and update the code to test the property coordinates
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property candidates (base name: "candidates")', function() {
      // uncomment below and update the code to test the property candidates
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property vehicleRegion (base name: "vehicle_region")', function() {
      // uncomment below and update the code to test the property vehicleRegion
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

    it('should have the property vehicle (base name: "vehicle")', function() {
      // uncomment below and update the code to test the property vehicle
      //var instane = new OpenalprApi.PlateDetails();
      //expect(instance).to.be();
    });

  });

}));
