/**
 * OpenALPR Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenalprApi) {
      root.OpenalprApi = {};
    }
    root.OpenalprApi.InlineResponse200ProcessingTime = factory(root.OpenalprApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse200ProcessingTime model module.
   * @module model/InlineResponse200ProcessingTime
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>InlineResponse200ProcessingTime</code>.
   * @alias module:model/InlineResponse200ProcessingTime
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse200ProcessingTime</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200ProcessingTime} obj Optional instance to populate.
   * @return {module:model/InlineResponse200ProcessingTime} The populated <code>InlineResponse200ProcessingTime</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('plates')) {
        obj['plates'] = ApiClient.convertToType(data['plates'], 'Number');
      }
      if (data.hasOwnProperty('vehicles')) {
        obj['vehicles'] = ApiClient.convertToType(data['vehicles'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Time spent processing all tasks (in milliseconds)
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;
  /**
   * Time spent performing license plate recognition (in milliseconds)
   * @member {Number} plates
   */
  exports.prototype['plates'] = undefined;
  /**
   * Time spent performing vehicle recognition (in milliseconds)
   * @member {Number} vehicles
   */
  exports.prototype['vehicles'] = undefined;



  return exports;
}));


