/**
 * OpenALPR Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200ProcessingTime', 'model/PlateDetails', 'model/RegionOfInterest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse200ProcessingTime'), require('./PlateDetails'), require('./RegionOfInterest'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenalprApi) {
      root.OpenalprApi = {};
    }
    root.OpenalprApi.InlineResponse200 = factory(root.OpenalprApi.ApiClient, root.OpenalprApi.InlineResponse200ProcessingTime, root.OpenalprApi.PlateDetails, root.OpenalprApi.RegionOfInterest);
  }
}(this, function(ApiClient, InlineResponse200ProcessingTime, PlateDetails, RegionOfInterest) {
  'use strict';




  /**
   * The InlineResponse200 model module.
   * @module model/InlineResponse200
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>InlineResponse200</code>.
   * @alias module:model/InlineResponse200
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200} obj Optional instance to populate.
   * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('processing_time')) {
        obj['processing_time'] = InlineResponse200ProcessingTime.constructFromObject(data['processing_time']);
      }
      if (data.hasOwnProperty('img_width')) {
        obj['img_width'] = ApiClient.convertToType(data['img_width'], 'Integer');
      }
      if (data.hasOwnProperty('img_height')) {
        obj['img_height'] = ApiClient.convertToType(data['img_height'], 'Integer');
      }
      if (data.hasOwnProperty('credit_cost')) {
        obj['credit_cost'] = ApiClient.convertToType(data['credit_cost'], 'Integer');
      }
      if (data.hasOwnProperty('credits_monthly_used')) {
        obj['credits_monthly_used'] = ApiClient.convertToType(data['credits_monthly_used'], 'Integer');
      }
      if (data.hasOwnProperty('credits_monthly_total')) {
        obj['credits_monthly_total'] = ApiClient.convertToType(data['credits_monthly_total'], 'Integer');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [PlateDetails]);
      }
      if (data.hasOwnProperty('regions_of_interest')) {
        obj['regions_of_interest'] = ApiClient.convertToType(data['regions_of_interest'], [RegionOfInterest]);
      }
      if (data.hasOwnProperty('epoch_time')) {
        obj['epoch_time'] = ApiClient.convertToType(data['epoch_time'], 'Number');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'Integer');
      }
      if (data.hasOwnProperty('data_type')) {
        obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse200ProcessingTime} processing_time
   */
  exports.prototype['processing_time'] = undefined;
  /**
   * Width of the uploaded image in pixels
   * @member {Integer} img_width
   */
  exports.prototype['img_width'] = undefined;
  /**
   * Height of the input image in pixels
   * @member {Integer} img_height
   */
  exports.prototype['img_height'] = undefined;
  /**
   * The number of API credits that were used to process this image
   * @member {Integer} credit_cost
   */
  exports.prototype['credit_cost'] = undefined;
  /**
   * The number of API credits used this month
   * @member {Integer} credits_monthly_used
   */
  exports.prototype['credits_monthly_used'] = undefined;
  /**
   * The maximum number of API credits available this month according to your plan
   * @member {Integer} credits_monthly_total
   */
  exports.prototype['credits_monthly_total'] = undefined;
  /**
   * @member {Array.<module:model/PlateDetails>} results
   */
  exports.prototype['results'] = undefined;
  /**
   * Describes the areas analyzed in the input image
   * @member {Array.<module:model/RegionOfInterest>} regions_of_interest
   */
  exports.prototype['regions_of_interest'] = undefined;
  /**
   * Epoch time that the image was processed in milliseconds
   * @member {Number} epoch_time
   */
  exports.prototype['epoch_time'] = undefined;
  /**
   * API format version
   * @member {Integer} version
   */
  exports.prototype['version'] = undefined;
  /**
   * Specifies the type of data in this response
   * @member {module:model/InlineResponse200.DataTypeEnum} data_type
   */
  exports.prototype['data_type'] = undefined;


  /**
   * Allowed values for the <code>data_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DataTypeEnum = {
    /**
     * value: "alpr_results"
     * @const
     */
    "alpr_results": "alpr_results",
    /**
     * value: "alpr_group"
     * @const
     */
    "alpr_group": "alpr_group",
    /**
     * value: "heartbeat"
     * @const
     */
    "heartbeat": "heartbeat"  };


  return exports;
}));


