/**
 * OpenALPR Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VehicleCandidate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VehicleCandidate'));
  } else {
    // Browser globals (root is window)
    if (!root.OpenalprApi) {
      root.OpenalprApi = {};
    }
    root.OpenalprApi.VehicleDetails = factory(root.OpenalprApi.ApiClient, root.OpenalprApi.VehicleCandidate);
  }
}(this, function(ApiClient, VehicleCandidate) {
  'use strict';




  /**
   * The VehicleDetails model module.
   * @module model/VehicleDetails
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>VehicleDetails</code>.
   * @alias module:model/VehicleDetails
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>VehicleDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VehicleDetails} obj Optional instance to populate.
   * @return {module:model/VehicleDetails} The populated <code>VehicleDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('color')) {
        obj['color'] = ApiClient.convertToType(data['color'], [VehicleCandidate]);
      }
      if (data.hasOwnProperty('make')) {
        obj['make'] = ApiClient.convertToType(data['make'], [VehicleCandidate]);
      }
      if (data.hasOwnProperty('make_model')) {
        obj['make_model'] = ApiClient.convertToType(data['make_model'], [VehicleCandidate]);
      }
      if (data.hasOwnProperty('body_type')) {
        obj['body_type'] = ApiClient.convertToType(data['body_type'], [VehicleCandidate]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/VehicleCandidate>} color
   */
  exports.prototype['color'] = undefined;
  /**
   * @member {Array.<module:model/VehicleCandidate>} make
   */
  exports.prototype['make'] = undefined;
  /**
   * @member {Array.<module:model/VehicleCandidate>} make_model
   */
  exports.prototype['make_model'] = undefined;
  /**
   * @member {Array.<module:model/VehicleCandidate>} body_type
   */
  exports.prototype['body_type'] = undefined;



  return exports;
}));


