/**
 * OpenALPR Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.openalpr.api.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * InlineResponse200ProcessingTime
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T16:12:49.437-05:00")
public class InlineResponse200ProcessingTime   {
  @SerializedName("total")
  private BigDecimal total = null;

  @SerializedName("plates")
  private BigDecimal plates = null;

  @SerializedName("vehicles")
  private BigDecimal vehicles = null;

  public InlineResponse200ProcessingTime total(BigDecimal total) {
    this.total = total;
    return this;
  }

   /**
   * Time spent processing all tasks (in milliseconds)
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "Time spent processing all tasks (in milliseconds)")
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(BigDecimal total) {
    this.total = total;
  }

  public InlineResponse200ProcessingTime plates(BigDecimal plates) {
    this.plates = plates;
    return this;
  }

   /**
   * Time spent performing license plate recognition (in milliseconds)
   * @return plates
  **/
  @ApiModelProperty(example = "null", value = "Time spent performing license plate recognition (in milliseconds)")
  public BigDecimal getPlates() {
    return plates;
  }

  public void setPlates(BigDecimal plates) {
    this.plates = plates;
  }

  public InlineResponse200ProcessingTime vehicles(BigDecimal vehicles) {
    this.vehicles = vehicles;
    return this;
  }

   /**
   * Time spent performing vehicle recognition (in milliseconds)
   * @return vehicles
  **/
  @ApiModelProperty(example = "null", value = "Time spent performing vehicle recognition (in milliseconds)")
  public BigDecimal getVehicles() {
    return vehicles;
  }

  public void setVehicles(BigDecimal vehicles) {
    this.vehicles = vehicles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200ProcessingTime inlineResponse200ProcessingTime = (InlineResponse200ProcessingTime) o;
    return Objects.equals(this.total, inlineResponse200ProcessingTime.total) &&
        Objects.equals(this.plates, inlineResponse200ProcessingTime.plates) &&
        Objects.equals(this.vehicles, inlineResponse200ProcessingTime.vehicles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, plates, vehicles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200ProcessingTime {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    plates: ").append(toIndentedString(plates)).append("\n");
    sb.append("    vehicles: ").append(toIndentedString(vehicles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

