/*
 * OpenALPR Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openalpr.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * PlateCandidate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-29T08:43:22.221-04:00")
public class PlateCandidate {
  @SerializedName("plate")
  private String plate = null;

  @SerializedName("confidence")
  private BigDecimal confidence = null;

  @SerializedName("matches_template")
  private Integer matchesTemplate = null;

  public PlateCandidate plate(String plate) {
    this.plate = plate;
    return this;
  }

   /**
   * Plate number
   * @return plate
  **/
  @ApiModelProperty(value = "Plate number")
  public String getPlate() {
    return plate;
  }

  public void setPlate(String plate) {
    this.plate = plate;
  }

  public PlateCandidate confidence(BigDecimal confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Confidence percentage that the plate number is correct
   * @return confidence
  **/
  @ApiModelProperty(value = "Confidence percentage that the plate number is correct")
  public BigDecimal getConfidence() {
    return confidence;
  }

  public void setConfidence(BigDecimal confidence) {
    this.confidence = confidence;
  }

  public PlateCandidate matchesTemplate(Integer matchesTemplate) {
    this.matchesTemplate = matchesTemplate;
    return this;
  }

   /**
   * Indicates whether the plate matched a regional text pattern
   * @return matchesTemplate
  **/
  @ApiModelProperty(value = "Indicates whether the plate matched a regional text pattern")
  public Integer getMatchesTemplate() {
    return matchesTemplate;
  }

  public void setMatchesTemplate(Integer matchesTemplate) {
    this.matchesTemplate = matchesTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlateCandidate plateCandidate = (PlateCandidate) o;
    return Objects.equals(this.plate, plateCandidate.plate) &&
        Objects.equals(this.confidence, plateCandidate.confidence) &&
        Objects.equals(this.matchesTemplate, plateCandidate.matchesTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plate, confidence, matchesTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlateCandidate {\n");
    
    sb.append("    plate: ").append(toIndentedString(plate)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    matchesTemplate: ").append(toIndentedString(matchesTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

