/*
 * OpenALPR Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.openalpr.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.openalpr.api.models.VehicleCandidate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VehicleDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-29T08:43:22.221-04:00")
public class VehicleDetails {
  @SerializedName("color")
  private List<VehicleCandidate> color = null;

  @SerializedName("make")
  private List<VehicleCandidate> make = null;

  @SerializedName("make_model")
  private List<VehicleCandidate> makeModel = null;

  @SerializedName("body_type")
  private List<VehicleCandidate> bodyType = null;

  public VehicleDetails color(List<VehicleCandidate> color) {
    this.color = color;
    return this;
  }

  public VehicleDetails addColorItem(VehicleCandidate colorItem) {
    if (this.color == null) {
      this.color = new ArrayList<VehicleCandidate>();
    }
    this.color.add(colorItem);
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(value = "")
  public List<VehicleCandidate> getColor() {
    return color;
  }

  public void setColor(List<VehicleCandidate> color) {
    this.color = color;
  }

  public VehicleDetails make(List<VehicleCandidate> make) {
    this.make = make;
    return this;
  }

  public VehicleDetails addMakeItem(VehicleCandidate makeItem) {
    if (this.make == null) {
      this.make = new ArrayList<VehicleCandidate>();
    }
    this.make.add(makeItem);
    return this;
  }

   /**
   * Get make
   * @return make
  **/
  @ApiModelProperty(value = "")
  public List<VehicleCandidate> getMake() {
    return make;
  }

  public void setMake(List<VehicleCandidate> make) {
    this.make = make;
  }

  public VehicleDetails makeModel(List<VehicleCandidate> makeModel) {
    this.makeModel = makeModel;
    return this;
  }

  public VehicleDetails addMakeModelItem(VehicleCandidate makeModelItem) {
    if (this.makeModel == null) {
      this.makeModel = new ArrayList<VehicleCandidate>();
    }
    this.makeModel.add(makeModelItem);
    return this;
  }

   /**
   * Get makeModel
   * @return makeModel
  **/
  @ApiModelProperty(value = "")
  public List<VehicleCandidate> getMakeModel() {
    return makeModel;
  }

  public void setMakeModel(List<VehicleCandidate> makeModel) {
    this.makeModel = makeModel;
  }

  public VehicleDetails bodyType(List<VehicleCandidate> bodyType) {
    this.bodyType = bodyType;
    return this;
  }

  public VehicleDetails addBodyTypeItem(VehicleCandidate bodyTypeItem) {
    if (this.bodyType == null) {
      this.bodyType = new ArrayList<VehicleCandidate>();
    }
    this.bodyType.add(bodyTypeItem);
    return this;
  }

   /**
   * Get bodyType
   * @return bodyType
  **/
  @ApiModelProperty(value = "")
  public List<VehicleCandidate> getBodyType() {
    return bodyType;
  }

  public void setBodyType(List<VehicleCandidate> bodyType) {
    this.bodyType = bodyType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleDetails vehicleDetails = (VehicleDetails) o;
    return Objects.equals(this.color, vehicleDetails.color) &&
        Objects.equals(this.make, vehicleDetails.make) &&
        Objects.equals(this.makeModel, vehicleDetails.makeModel) &&
        Objects.equals(this.bodyType, vehicleDetails.bodyType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, make, makeModel, bodyType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleDetails {\n");
    
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    make: ").append(toIndentedString(make)).append("\n");
    sb.append("    makeModel: ").append(toIndentedString(makeModel)).append("\n");
    sb.append("    bodyType: ").append(toIndentedString(bodyType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

