/* 
 * OpenALPR Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenAlprApi.Api;
using OpenAlprApi.Model;
using OpenAlprApi.Client;
using System.Reflection;

namespace OpenAlprApi.Test
{
    /// <summary>
    ///  Class for testing InlineResponse200
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse200Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200
        //private InlineResponse200 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse200
            //instance = new InlineResponse200();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse200
        /// </summary>
        [Test]
        public void InlineResponse200InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse200
            //Assert.IsInstanceOfType<InlineResponse200> (instance, "variable 'instance' is a InlineResponse200");
        }

        /// <summary>
        /// Test the property 'ProcessingTime'
        /// </summary>
        [Test]
        public void ProcessingTimeTest()
        {
            // TODO unit test for the property 'ProcessingTime'
        }
        /// <summary>
        /// Test the property 'ImgWidth'
        /// </summary>
        [Test]
        public void ImgWidthTest()
        {
            // TODO unit test for the property 'ImgWidth'
        }
        /// <summary>
        /// Test the property 'ImgHeight'
        /// </summary>
        [Test]
        public void ImgHeightTest()
        {
            // TODO unit test for the property 'ImgHeight'
        }
        /// <summary>
        /// Test the property 'CreditCost'
        /// </summary>
        [Test]
        public void CreditCostTest()
        {
            // TODO unit test for the property 'CreditCost'
        }
        /// <summary>
        /// Test the property 'CreditsMonthlyUsed'
        /// </summary>
        [Test]
        public void CreditsMonthlyUsedTest()
        {
            // TODO unit test for the property 'CreditsMonthlyUsed'
        }
        /// <summary>
        /// Test the property 'CreditsMonthlyTotal'
        /// </summary>
        [Test]
        public void CreditsMonthlyTotalTest()
        {
            // TODO unit test for the property 'CreditsMonthlyTotal'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'RegionsOfInterest'
        /// </summary>
        [Test]
        public void RegionsOfInterestTest()
        {
            // TODO unit test for the property 'RegionsOfInterest'
        }
        /// <summary>
        /// Test the property 'EpochTime'
        /// </summary>
        [Test]
        public void EpochTimeTest()
        {
            // TODO unit test for the property 'EpochTime'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }

    }

}
