/* 
 * OpenALPR Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenAlprApi.Api;
using OpenAlprApi.Model;
using OpenAlprApi.Client;
using System.Reflection;

namespace OpenAlprApi.Test
{
    /// <summary>
    ///  Class for testing VehicleDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleDetailsTests
    {
        // TODO uncomment below to declare an instance variable for VehicleDetails
        //private VehicleDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VehicleDetails
            //instance = new VehicleDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VehicleDetails
        /// </summary>
        [Test]
        public void VehicleDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VehicleDetails
            //Assert.IsInstanceOfType<VehicleDetails> (instance, "variable 'instance' is a VehicleDetails");
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Make'
        /// </summary>
        [Test]
        public void MakeTest()
        {
            // TODO unit test for the property 'Make'
        }
        /// <summary>
        /// Test the property 'MakeModel'
        /// </summary>
        [Test]
        public void MakeModelTest()
        {
            // TODO unit test for the property 'MakeModel'
        }
        /// <summary>
        /// Test the property 'BodyType'
        /// </summary>
        [Test]
        public void BodyTypeTest()
        {
            // TODO unit test for the property 'BodyType'
        }

    }

}
