/**
 * OpenALPR Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.openalpr.api;

import com.openalpr.api.invoker.ApiException;
import com.openalpr.api.models.InlineResponse200;
import com.openalpr.api.models.InlineResponse400;
import java.io.File;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * Send an image for OpenALPR to analyze and provide metadata back The image is sent as base64 encoded bytes. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void recognizeBytesTest() throws ApiException {
        String imageBytes = null;
        String secretKey = null;
        String country = null;
        Integer recognizeVehicle = null;
        String state = null;
        Integer returnImage = null;
        Integer topn = null;
        String prewarp = null;
        // InlineResponse200 response = api.recognizeBytes(imageBytes, secretKey, country, recognizeVehicle, state, returnImage, topn, prewarp);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Send an image for OpenALPR to analyze and provide metadata back The image is sent as a file using a form data POST 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void recognizeFileTest() throws ApiException {
        File image = null;
        String secretKey = null;
        String country = null;
        Integer recognizeVehicle = null;
        String state = null;
        Integer returnImage = null;
        Integer topn = null;
        String prewarp = null;
        // InlineResponse200 response = api.recognizeFile(image, secretKey, country, recognizeVehicle, state, returnImage, topn, prewarp);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Send an image for OpenALPR to analyze and provide metadata back The image is sent as a URL.  The OpenALPR service will download the image  and process it 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void recognizeUrlTest() throws ApiException {
        String imageUrl = null;
        String secretKey = null;
        String country = null;
        Integer recognizeVehicle = null;
        String state = null;
        Integer returnImage = null;
        Integer topn = null;
        String prewarp = null;
        // InlineResponse200 response = api.recognizeUrl(imageUrl, secretKey, country, recognizeVehicle, state, returnImage, topn, prewarp);

        // TODO: test validations
    }
    
}
