<?php
/**
 * InlineResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenALPR Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200Test Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse200
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "InlineResponse200"
     */
    public function testInlineResponse200()
    {

    }

    /**
     * Test attribute "processing_time"
     */
    public function testPropertyProcessingTime()
    {

    }

    /**
     * Test attribute "img_width"
     */
    public function testPropertyImgWidth()
    {

    }

    /**
     * Test attribute "img_height"
     */
    public function testPropertyImgHeight()
    {

    }

    /**
     * Test attribute "credit_cost"
     */
    public function testPropertyCreditCost()
    {

    }

    /**
     * Test attribute "credits_monthly_used"
     */
    public function testPropertyCreditsMonthlyUsed()
    {

    }

    /**
     * Test attribute "credits_monthly_total"
     */
    public function testPropertyCreditsMonthlyTotal()
    {

    }

    /**
     * Test attribute "results"
     */
    public function testPropertyResults()
    {

    }

    /**
     * Test attribute "regions_of_interest"
     */
    public function testPropertyRegionsOfInterest()
    {

    }

    /**
     * Test attribute "epoch_time"
     */
    public function testPropertyEpochTime()
    {

    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {

    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {

    }

}
