//
// InlineResponse200ProcessingTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse200ProcessingTime: JSONEncodable {
    /** Time spent processing all tasks (in milliseconds) */
    public var total: Double?
    /** Time spent performing license plate recognition (in milliseconds) */
    public var plates: Double?
    /** Time spent performing vehicle recognition (in milliseconds) */
    public var vehicles: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total
        nillableDictionary["plates"] = self.plates
        nillableDictionary["vehicles"] = self.vehicles
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
