//
// PlateCandidate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PlateCandidate: JSONEncodable {
    /** Plate number */
    public var plate: String?
    /** Confidence percentage that the plate number is correct */
    public var confidence: Double?
    /** Indicates whether the plate matched a regional text pattern */
    public var matchesTemplate: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["plate"] = self.plate
        nillableDictionary["confidence"] = self.confidence
        nillableDictionary["matches_template"] = self.matchesTemplate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
