//
// RegionOfInterest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RegionOfInterest: JSONEncodable {
    public var x: Int32?
    public var y: Int32?
    public var width: Int32?
    public var height: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["x"] = self.x?.encodeToJSON()
        nillableDictionary["y"] = self.y?.encodeToJSON()
        nillableDictionary["width"] = self.width?.encodeToJSON()
        nillableDictionary["height"] = self.height?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
