//
// VehicleDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class VehicleDetails: JSONEncodable {
    public var color: [VehicleCandidate]?
    public var make: [VehicleCandidate]?
    public var makeModel: [VehicleCandidate]?
    public var bodyType: [VehicleCandidate]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["color"] = self.color?.encodeToJSON()
        nillableDictionary["make"] = self.make?.encodeToJSON()
        nillableDictionary["make_model"] = self.makeModel?.encodeToJSON()
        nillableDictionary["body_type"] = self.bodyType?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
