/* 
 * OpenALPR Cloud API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace OpenAlprApi.Model
{
    /// <summary>
    /// PlateCandidate
    /// </summary>
    [DataContract]
    public partial class PlateCandidate :  IEquatable<PlateCandidate>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlateCandidate" /> class.
        /// </summary>
        /// <param name="Plate">Plate number.</param>
        /// <param name="Confidence">Confidence percentage that the plate number is correct.</param>
        /// <param name="MatchesTemplate">Indicates whether the plate matched a regional text pattern.</param>
        public PlateCandidate(string Plate = null, decimal? Confidence = null, int? MatchesTemplate = null)
        {
            this.Plate = Plate;
            this.Confidence = Confidence;
            this.MatchesTemplate = MatchesTemplate;
        }
        
        /// <summary>
        /// Plate number
        /// </summary>
        /// <value>Plate number</value>
        [DataMember(Name="plate", EmitDefaultValue=false)]
        public string Plate { get; set; }
        /// <summary>
        /// Confidence percentage that the plate number is correct
        /// </summary>
        /// <value>Confidence percentage that the plate number is correct</value>
        [DataMember(Name="confidence", EmitDefaultValue=false)]
        public decimal? Confidence { get; set; }
        /// <summary>
        /// Indicates whether the plate matched a regional text pattern
        /// </summary>
        /// <value>Indicates whether the plate matched a regional text pattern</value>
        [DataMember(Name="matches_template", EmitDefaultValue=false)]
        public int? MatchesTemplate { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlateCandidate {\n");
            sb.Append("  Plate: ").Append(Plate).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("  MatchesTemplate: ").Append(MatchesTemplate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PlateCandidate);
        }

        /// <summary>
        /// Returns true if PlateCandidate instances are equal
        /// </summary>
        /// <param name="other">Instance of PlateCandidate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlateCandidate other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Plate == other.Plate ||
                    this.Plate != null &&
                    this.Plate.Equals(other.Plate)
                ) && 
                (
                    this.Confidence == other.Confidence ||
                    this.Confidence != null &&
                    this.Confidence.Equals(other.Confidence)
                ) && 
                (
                    this.MatchesTemplate == other.MatchesTemplate ||
                    this.MatchesTemplate != null &&
                    this.MatchesTemplate.Equals(other.MatchesTemplate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Plate != null)
                    hash = hash * 59 + this.Plate.GetHashCode();
                if (this.Confidence != null)
                    hash = hash * 59 + this.Confidence.GetHashCode();
                if (this.MatchesTemplate != null)
                    hash = hash * 59 + this.MatchesTemplate.GetHashCode();
                return hash;
            }
        }
    }

}
